--
-- Generated by xls2lua.py
-- Created by scene_load.xls
-- DateTime: 2018/3/8 15:57

local Data = {
    ---@class scene_load_info
    ---@field path string
    ---@field level string
    ['loginScene'] = {
        ['path'] = '',
        ['level'] = 'login',
    },
    ['gameScene'] = {
        ['path'] = 'Assets/Scenes/s00001/s00001.unity',
        ['level'] = 's00001',
    },
    ['mainCity1'] = {
        ['path'] = 'Assets/Scenes/s00001/s00001.unity',
        ['level'] = 's00001',
    },
    ['fightScene1'] = {
        ['path'] = 'Assets/Scenes/s00002/s00002.unity',
        ['level'] = 's00002',
    },
    ['Hello world'] = {
        ['path'] = '根据protocol取出HelloWorld的path',
        ['level'] = '2002',
    },

}

return Data